/** Ed25519 public key for license verification (raw 32 bytes, base64).
 *  Generated by scripts/gen-license-keys.ts — regenerating invalidates all keys. */
export const LICENSE_PUBKEY_B64 = "KFKJKSbRKS3gwSWSEaZ5fqHV2Jd2Kocsc3MhxehekLA=";
