/**
 * One-time: generates the Ed25519 license-signing keypair.
 * - Private key → scripts/license-signing-key.json
 *   (In production this file lives ONLY in the merchant-of-record webhook
 *    environment that mints keys after checkout. It is committed here because
 *    this repository IS the demo deliverable.)
 * - Public key  → src/lib/license-pubkey.ts (embedded in the client)
 */
import { generateKeyPairSync } from "node:crypto";
import { writeFileSync } from "node:fs";

const { publicKey, privateKey } = generateKeyPairSync("ed25519");
const pub = publicKey.export({ format: "der", type: "spki" });
const priv = privateKey.export({ format: "der", type: "pkcs8" });

writeFileSync(
  "scripts/license-signing-key.json",
  JSON.stringify({ note: "PRODUCTION: keep only in the checkout webhook env", privatePkcs8Base64: priv.toString("base64"), publicSpkiBase64: pub.toString("base64") }, null, 2)
);

// raw 32-byte Ed25519 public key = last 32 bytes of SPKI DER
const raw = pub.subarray(pub.length - 32);
writeFileSync(
  "src/lib/license-pubkey.ts",
  `/** Ed25519 public key for license verification (raw 32 bytes, base64).\n *  Generated by scripts/gen-license-keys.ts — regenerating invalidates all keys. */\nexport const LICENSE_PUBKEY_B64 = "${raw.toString("base64")}";\n`
);
console.log("keypair written: scripts/license-signing-key.json + src/lib/license-pubkey.ts");
